// Generated by CoffeeScript 1.6.2
(function() {
  exports.register = function(app) {
    return app.get('/', function(req, res) {
      return res.render('../reports/dashboard/index', {});
    });
  };

}).call(this);
