// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, http, path;

  express = require('express');

  path = require('path');

  http = require('http');

  console.log('hello 2');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + '/views');

  app.set('view engine', 'ejs');

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express.favicon());

  app.use('/chart-modules', express["static"]('chart-modules'));

  app.use('/libs', express["static"]('libs'));

  http.createServer(app).listen(app.get('port'), function() {
    return console.log("express started at port " + app.get('port'));
  });

}).call(this);
